export const CHANGE_SEARCH_ACTIVE_PAGE = 'rd_books/CHANGE_SEARCH_ACTIVE_PAGE';

export const REQUEST_SEARCH_LOAD = 'rd_books/Search/REQUEST_SEARCH_LOAD';

export const SET_SEARCH_STATUS_LOADING = 'rd_books/SET_SEARCH_STATUS_LOADING';
export const SET_SEARCH_STATUS_ERROR = 'rd_books/SET_SEARCH_STATUS_ERROR';
export const SET_SEARCH_STATUS_SUCCESS = 'rd_books/SET_SEARCH_STATUS_SUCCESS';

export const ADD_NEW_BOOK_FAVORITE = 'rd_books/ADD_NEW_BOOK_FAVORITE';
export const REMOVE_NEW_BOOK_FAVORITE = 'rd_books/REMOVE_NEW_BOOK_FAVORITE';
