export const CHANGE_FAVORITE_ACTIVE_PAGE = 'rd_books/CHANGE_FAVORITE_ACTIVE_PAGE';

export const REQUEST_FAVORITE_LOAD = 'rd_books/REQUEST_FAVORITE_LOAD';

export const SET_FAVORITE_STATUS_LOADING = 'rd_books/SET_FAVORITE_STATUS_LOADING';
export const SET_FAVORITE_STATUS_ERROR = 'rd_books/SET_FAVORITE_STATUS_ERROR';
export const SET_FAVORITE_STATUS_SUCCESS = 'rd_books/SET_FAVORITE_STATUS_SUCCESS';
